services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: locationcrud-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Password123
      - MSSQL_PID=Express
    ports:
      - "5433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - locationcrud-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P YourStrong@Password123 -C -Q 'SELECT 1'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s


  locationcrud-app:
    build: .
    container_name: locationcrud-app
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=LocationManagerDb;User Id=sa;Password=YourStrong@Password123;TrustServerCertificate=true;MultipleActiveResultSets=true
    ports:
      - "8080:80"
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - locationcrud-network
    restart: unless-stopped
    volumes:
      - app_logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s


  nginx:
    image: nginx:latest
    container_name: locationcrud-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      locationcrud-app:
        condition: service_healthy
    networks:
      - locationcrud-network
    restart: unless-stopped


  apache:
    image: httpd:latest
    container_name: locationcrud-apache
    ports:
      - "8081:80"
    volumes:
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
    depends_on:
      locationcrud-app:
        condition: service_healthy
    networks:
      - locationcrud-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  sqlserver_data:
    driver: local
  app_logs:
    driver: local

networks:
  locationcrud-network:
    driver: bridge
