name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Run tests
        run: dotnet test --no-restore

      - name: Publish
        run: dotnet publish -c Release -o published

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: drop
          path: published/

  build-and-push-image:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/locationcrud-app:latest

  deploy-local:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull latest Docker image
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/locationcrud-app:latest

      - name: Stop and remove old container
        run: |
          docker rm -f locationcrud-app || true

      - name: Run container locally
        run: |
          docker run -d \
            --name locationcrud-app \
            -p 5000:80 \
            ghcr.io/${{ github.repository_owner }}/locationcrud-app:latest

      - name: Smoke-test HTTP endpoint
        run: |
          echo "Waiting for container to be up..."
          for i in {1..10}; do
            if curl -s -o /dev/null -w "%{http_code}" http://localhost:5000 | grep -q "200"; then
              echo "➜ Application is responding!"
              exit 0
            else
              echo "Waiting... ($i/10)"
              sleep 3
            fi
          done
          echo "❌ Application did not respond in time."; exit 1
