name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Run tests
        run: dotnet test --no-restore

      - name: Publish
        run: dotnet publish -c Release -o published

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: drop
          path: published/

  build-and-push-image:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/locationcrud-app:latest

  deploy:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install SSH key and known_hosts
        run: |
          # Create .ssh folder
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          # Write the private key, preserving all newlines
          printf '%s\n' "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Add GitHub RSA host key (ignore errors)
          ssh-keyscan -t rsa github.com 2>/dev/null >> ~/.ssh/known_hosts || true
          # Add your EC2 host's RSA key (ignore errors)
          ssh-keyscan -t rsa 39.45.18.6 2>/dev/null >> ~/.ssh/known_hosts || true

      - name: Deploy over SSH
        run: |
          ssh -o StrictHostKeyChecking=yes ubuntu@39.45.18.6 << 'EOF'
            docker pull ghcr.io/${{ github.repository_owner }}/locationcrud-app:latest
            docker rm -f locationcrud-app || true
            docker run -d \
              --name locationcrud-app \
              -p 5000:80 \
              ghcr.io/${{ github.repository_owner }}/locationcrud-app:latest
          EOF
