# .github/workflows/ci-cd.yml
name: CI/CD Pipeline

permissions:
  contents: read       # for actions/checkout
  packages: write      # to push Docker images to GHCR
  id-token: write      # if you use OIDC or other token needs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Run tests
        run: dotnet test --no-restore --verbosity normal

      - name: Publish
        run: dotnet publish -c Release -o published

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: drop
          path: published/

  build-and-push-image:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/locationcrud-app:latest
            ghcr.io/${{ github.repository_owner }}/locationcrud-app:${{ github.sha }}

  deploy:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 39.45.18.6 >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh deploy@39.45.18.6 "\
            docker pull ghcr.io/${{ github.repository_owner }}/locationcrud-app:latest && \
            docker rm -f locationcrud-app || true && \
            docker run -d --name locationcrud-app -p 5000:80 \
              ghcr.io/${{ github.repository_owner }}/locationcrud-app:latest\
          "
